# Generated by Django 4.2.5 on 2023-09-17 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='advertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='images')),
                ('price', models.BigIntegerField()),
                ('phone_number', models.BigIntegerField()),
                ('post_date', models.DateField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'advertise',
                'ordering': ['-post_date'],
            },
        ),
    ]
