# Generated by Django 4.2.5 on 2023-09-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='product_img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
