# Generated by Django 4.2.4 on 2023-09-20 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_salomatliks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='salomatliks',
        ),
    ]
